### ISSUE TITLE
More English Translations? 英文翻译

### ISSUE THREAD

**Issue by grantwwu** [Houdou/prts-map#41]
I really appreciate the great resource that is map.ark-nights.com. It has helped me a lot with IS#2. Would it be possible for me to help translate the titles of some of the newer stages?

我非常喜欢map.ark-nights.com。帮了我很大忙。我可以帮您翻译新的地图名字吗？对不起我的中文不太好。

**Comment by Houdou** [comment]
Thank you for your support. I do have scripts to patch i18n resources for most of levels (except CC levels)
But the data source for IS#2 changed, and I forgot to update the scripts correspondingly. Sorry for not being aware of it for a long time.

Definitely no need manual effort for translation, I can take care of it.

Btw, 你的中文讲得很好，表达的意思很准确 👍

**Comment by Houdou** [comment]
@grantwwu 
![image](https://user-images.githubusercontent.com/6690811/182829682-ebfb402a-63e3-4996-b501-53ae962016df.png)

Updated.
Expecting that there are some levels still not translated because those are upcoming monthly updates for IS mode.
So there is no official translation yet, and shouldn't bother that much as they are not available in EN/JP server for now.

I will update it as soon as those updates go live.
